[package]
name = "aoc_2023_16"
version = "0.1.0"
authors = ["Georg Begerow <gbegerow+aoc@gmail.com>"]
edition = "2024"

[dependencies]
rstest = {workspace = true}
crossterm= {workspace = true, optional=true}
ratatui = {workspace = true, optional=true}

[features]
default=["viz"]
viz=["dep:crossterm","dep:ratatui"]

